name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag report-service:${{github.run_number}};
        docker image tag report-service:${{github.run_number}}  registry.crazedencoder.com/${{github.run_number}}/report-service:${{github.run_number}} ;
        docker image push registry.crazedencoder.com/${{github.run_number}}/report-service:${{github.run_number}};
